// Company branding constants
export const COMPANY = {
  name: "Industrial Solutions",
  email: "info@company.uz",
  phone: "+998 (71) 200-00-00",
  address: "Tashkent, Uzbekistan",
  colors: {
    primary: "#1A2C59", // Deep blue
    accent: "#F9C500", // Gold
  },
}

export const PRODUCTS = [
  {
    id: 1,
    name: "Industrial Pump System",
    description:
      "High-performance pump system designed for continuous industrial operation with minimal maintenance.",
    image: "/industrial-pump-system.jpg",
    price: "$5,000",
    category: "pumps",
    material: "Stainless Steel",
    size: "120x80x90 cm",
    weight: "250 kg",
    madeIn: "Namangan",
    specs: ["Flow Rate: 500 GPM", "Pressure: 150 PSI", "Power: 15 kW"],
  },
  {
    id: 2,
    name: "Conveyor Belt Assembly",
    description:
      "Durable and efficient conveyor system for material handling in production lines.",
    image: "/conveyor-belt-assembly.jpg",
    price: "$8,500",
    category: "conveyors",
    material: "Carbon Steel + Rubber",
    size: "Length: 50m, Width: 1.2m",
    weight: "1,200 kg",
    madeIn: "Namangan",
    specs: ["Speed: 2 m/s", "Load Capacity: 1000 kg/h", "Motor Power: 7.5 kW"],
  },
  {
    id: 3,
    name: "Hydraulic Press Machine",
    description:
      "Heavy-duty hydraulic press for precision metal forming and shaping operations.",
    image: "/hydraulic-press-industrial.jpg",
    price: "$12,000",
    category: "hydraulics",
    material: "Cast Iron Frame",
    size: "180x120x220 cm",
    weight: "2,800 kg",
    madeIn: "Namangan",
    specs: ["Force: 500 tons", "Stroke: 1.5m", "Power: 30 kW"],
  },
  {
    id: 4,
    name: "Control Panel System",
    description:
      "Advanced automation control panel with modular circuit design and integrated safety features.",
    image: "/control-panel-automation.jpg",
    price: "$3,500",
    category: "automation",
    material: "Aluminum & PVC Housing",
    size: "100x60x40 cm",
    weight: "80 kg",
    madeIn: "Namangan",
    specs: ["Inputs: 32", "Outputs: 16", "Communication: Ethernet, RS485"],
  },
  {
    id: 5,
    name: "Cooling Tower Unit",
    description:
      "High-efficiency cooling system designed for heat exchange in large-scale industries.",
    image: "/cooling-tower-unit.jpg",
    price: "$9,000",
    category: "pumps",
    material: "Fiberglass Reinforced Plastic (FRP)",
    size: "200x200x300 cm",
    weight: "1,000 kg",
    madeIn: "Namangan",
    specs: ["Cooling Capacity: 300 TR", "Water Flow: 600 m³/h", "Fan Motor: 10 HP"],
  },
  {
    id: 6,
    name: "Roller Conveyor Line",
    description:
      "Industrial-grade roller conveyor for heavy load transfer in assembly lines.",
    image: "/roller-conveyor-line.jpg",
    price: "$6,800",
    category: "conveyors",
    material: "Galvanized Steel Rollers",
    size: "Length: 30m, Width: 0.8m",
    weight: "850 kg",
    madeIn: "Namangan",
    specs: ["Roller Diameter: 60 mm", "Motor Power: 3 kW", "Speed: 1.5 m/s"],
  },
  {
    id: 7,
    name: "Hydraulic Power Pack",
    description:
      "Compact hydraulic power unit used for driving cylinders and presses.",
    image: "/hydraulic-power-pack.jpg",
    price: "$4,200",
    category: "hydraulics",
    material: "Steel Tank + Cast Iron Pump",
    size: "80x50x90 cm",
    weight: "160 kg",
    madeIn: "Namangan",
    specs: ["Flow: 40 L/min", "Pressure: 250 bar", "Motor: 5.5 kW"],
  },
  {
    id: 8,
    name: "PLC Automation Cabinet",
    description:
      "Smart programmable logic controller cabinet for industrial automation systems.",
    image: "/plc-automation-cabinet.jpg",
    price: "$5,800",
    category: "automation",
    material: "Powder-Coated Steel",
    size: "120x80x60 cm",
    weight: "95 kg",
    madeIn: "Namangan",
    specs: ["PLC: Siemens S7-1200", "Communication: Modbus TCP", "Voltage: 220V"],
  },
  {
    id: 9,
    name: "Centrifugal Pump",
    description:
      "Reliable centrifugal pump optimized for fluid transport and industrial processes.",
    image: "/centrifugal-pump.jpg",
    price: "$3,900",
    category: "pumps",
    material: "Stainless Steel 304",
    size: "60x40x50 cm",
    weight: "90 kg",
    madeIn: "Namangan",
    specs: ["Flow Rate: 350 L/min", "Pressure: 10 bar", "Efficiency: 92%"],
  },
  {
    id: 10,
    name: "Robotic Arm System",
    description:
      "High-precision robotic arm for automated manufacturing and material handling.",
    image: "/robotic-arm-industrial.jpg",
    price: "$15,000",
    category: "automation",
    material: "Aluminum Alloy + Servo Actuators",
    size: "Height: 2.1m, Reach: 1.5m",
    weight: "300 kg",
    madeIn: "Namangan",
    specs: ["Payload: 25 kg", "Axis: 6 DOF", "Accuracy: ±0.05 mm"],
  },
  {
    id: 11,
    name: "Hydraulic Cylinder Assembly",
    description:
      "Custom-built hydraulic cylinder for industrial presses, cranes, and lifting systems.",
    image: "/hydraulic-cylinder-assembly.jpg",
    price: "$2,800",
    category: "hydraulics",
    material: "Hardened Steel with Chrome Plating",
    size: "Diameter: 150 mm, Stroke: 800 mm",
    weight: "180 kg",
    madeIn: "Namangan",
    specs: ["Pressure: 300 bar", "Seal Type: Double-acting", "Mounting: Flange"],
  },
  {
    id: 12,
    name: "Smart Conveyor Control System",
    description:
      "AI-assisted conveyor monitoring and control unit for next-gen smart factories.",
    image: "/smart-conveyor-control.jpg",
    price: "$7,400",
    category: "automation",
    material: "Aluminum & Industrial PCB",
    size: "90x60x50 cm",
    weight: "65 kg",
    madeIn: "Namangan",
    specs: ["AI Optimization", "IoT Sensor Support", "Cloud Integration Ready"],
  },
];

export const NEWS = [
  {
    id: 1,
    title: "New Factory Expansion Announced",
    date: "2024-10-15",
    image: "/factory-expansion-industrial.jpg",
    category: "announcements",
    excerpt: "We are excited to announce the expansion of our manufacturing facility to meet growing demand.",
    content: "Our new facility will increase production capacity by 40% and create 200 new jobs in the region. The expansion includes advanced CNC systems, improved logistics infrastructure, and an R&D laboratory.",
  },
  {
    id: 2,
    title: "Innovation in Hydraulic Technology",
    date: "2024-10-10",
    image: "/hydraulic-technology-innovation.jpg",
    category: "innovations",
    excerpt: "Introducing our latest hydraulic system with improved efficiency and reduced energy consumption.",
    content: "The new system reduces energy consumption by 25% while maintaining superior performance standards. It’s part of our mission to bring smarter, greener hydraulic technologies to industrial production.",
  },
  {
    id: 3,
    title: "International Trade Exhibition Success",
    date: "2024-10-05",
    image: "/trade-exhibition-industrial.jpg",
    category: "events",
    excerpt: "Our company showcased cutting-edge products at the International Industrial Trade Exhibition.",
    content: "We received multiple awards for innovation and design excellence at the prestigious event. Our booth attracted international clients and strengthened global business relations.",
  },
  {
    id: 4,
    title: "Automation Upgrade in Production Line",
    date: "2024-09-22",
    image: "/automation-upgrade-factory.jpg",
    category: "technology",
    excerpt: "We have integrated a new automated conveyor system to optimize manufacturing speed.",
    content: "The automation upgrade has boosted productivity by 30% and reduced human error significantly. The new system is fully compatible with our PLC-based control panels and monitoring tools.",
  },
  {
    id: 5,
    title: "Employee Training Program Launched",
    date: "2024-09-10",
    image: "/employee-training-industrial.jpg",
    category: "announcements",
    excerpt: "A comprehensive technical training program has been introduced for our engineering team.",
    content: "The program focuses on safety protocols, advanced machinery operation, and digital manufacturing systems. Over 120 employees are enrolled in the first phase of the program.",
  },
  {
    id: 6,
    title: "Sustainability Initiative Introduced",
    date: "2024-08-29",
    image: "/sustainability-initiative-factory.jpg",
    category: "sustainability",
    excerpt: "We are committed to reducing our carbon footprint through green manufacturing practices.",
    content: "Our new solar energy system will power 60% of factory operations, cutting emissions drastically. Additionally, waste recycling initiatives are being rolled out across all departments.",
  },
  {
    id: 7,
    title: "New Partnership with German Engineering Firm",
    date: "2024-08-15",
    image: "/german-partnership-industrial.jpg",
    category: "partnerships",
    excerpt: "We have signed a long-term partnership with a leading German industrial solutions provider.",
    content: "The collaboration will focus on developing smart automation technologies and export expansion. Joint research teams are already working on modular robotic systems for industrial use.",
  },
  {
    id: 8,
    title: "NamanganMash Wins Industrial Excellence Award",
    date: "2024-08-01",
    image: "/industrial-excellence-award.jpg",
    category: "awards",
    excerpt: "We are proud to receive the Industrial Excellence Award 2024 for innovation and performance.",
    content: "The award recognizes our dedication to innovation, quality control, and customer satisfaction. This marks the third consecutive year NamanganMash has been honored at the national level.",
  },
  {
    id: 9,
    title: "New Product Line: Conveyor Series X",
    date: "2024-07-20",
    image: "/conveyor-series-x.jpg",
    category: "products",
    excerpt: "Our new Conveyor Series X is designed for heavy-duty performance and longer durability.",
    content: "The Series X features modular belts, smart sensors, and low-energy motors for sustainable production. Pre-orders have already started for both domestic and international clients.",
  },
  {
    id: 10,
    title: "Local Community Engagement Program",
    date: "2024-07-10",
    image: "/community-engagement-factory.jpg",
    category: "community",
    excerpt: "NamanganMash continues to support local communities with education and social programs.",
    content: "We’ve donated equipment and sponsored scholarships for technical university students in the region. The program also includes internship opportunities for top-performing students.",
  },
  {
    id: 11,
    title: "Digital Twin Technology Implementation",
    date: "2024-06-25",
    image: "/digital-twin-implementation.jpg",
    category: "technology",
    excerpt: "We’ve adopted digital twin technology to simulate and optimize production workflows in real time.",
    content: "This innovation allows us to monitor performance metrics and predict maintenance needs before failures occur. It marks a major step toward Industry 4.0 compliance at NamanganMash.",
  },
  {
    id: 12,
    title: "New Export Agreement with Central Asian Partners",
    date: "2024-06-10",
    image: "/central-asia-export-agreement.jpg",
    category: "partnerships",
    excerpt: "NamanganMash has entered a regional export agreement with Central Asian industrial companies.",
    content: "The new agreement strengthens regional trade ties and provides access to a wider industrial market. Our export volume is expected to grow by 50% over the next two years.",
  },
]
